"""empty message

Revision ID: f9c2192818ba
Revises: 
Create Date: 2019-09-09 22:06:29.192017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c2192818ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Unicode(length=140), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('moneytotal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Unicode(length=140), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moneytotal')
    op.drop_table('money')
    # ### end Alembic commands ###
